### ISSUE TITLE
[Question]: Is RxJava - easy question #3 a bug?

### ISSUE THREAD

**Issue by arriolac** [artem-zinnatullin/droidcon-nyc-2017-puzzlers#3]
The documentation for `PublishSubject` states that a `PublishSubject` is a "Subject that, once an Observer has subscribed, emits all subsequently observed items to the subscriber."

From this definition it seems that the behavior observed in the the [RxJava easy question #3](https://github.com/artem-zinnatullin/droidcon-nyc-2017-puzzlers/blob/master/puzzlers/src/test/kotlin/com/lyft/droidconnyc2017/puzzlers/rxjava/easy/EasyRxPuzzler3.kt) is a bug in the framework. Either that, or this behavior should be updated in the documentation.

What are your thoughts on this?

**Comment by artem-zinnatullin** [comment]
Errors are terminal events thus they have to be delivered to new observers even if they subscribe too late, doc might state that clearer I guess :)
